import json
import requests
import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Literal
from google import genai
from google.genai import types
from dotenv import load_dotenv
from fastapi.middleware.cors import CORSMiddleware
from crypto_tools import CRYPTO_TOOLS, ADVANCED_CRYPTO_TOOLS, _normalize_ticker 
import yfinance as yf 

load_dotenv()

# 2. The Blueprint
class TechnicalAssessment(BaseModel):
    ticker: str
    current_price: float
    stance: Literal["BULLISH", "BEARISH", "NEUTRAL"]
    direct_verdict: str
    risk_assessment: str
    tactical_recommendation: str
    key_observations: list[str]
    disclaimer: str # <--- Add this field

# 3. Initialize Web Server and AI
app = FastAPI()
client = genai.Client()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class QueryRequest(BaseModel):
    query: str

# ----------------------------------------------------------------------
# AI MODEL MARKET ANALYSIS ENDPOINT
# ----------------------------------------------------------------------
@app.post("/api/analyze")
def analyze_market(request: QueryRequest):
    print(f"\n======================================")
    print(f"Incoming user query: {request.query}")
    
    all_tools = CRYPTO_TOOLS + ADVANCED_CRYPTO_TOOLS
    
    system_prompt = (
        "You are an elite quantitative crypto strategist. "
        "You have access to 8 advanced market tools. "
        "1. Run the relevant tools to gather data. "
        "2. Directly answer their question in 'direct_verdict' using risk/reward principles. "
        "3. Evaluate the downside in 'risk_assessment'. "
        "4. Outline clear tactical next steps in 'tactical_recommendation'. "
        "5. Leave the 'disclaimer' field empty; the system will auto-fill it."
    )
    
    config = types.GenerateContentConfig(
        system_instruction=system_prompt, 
        tools=all_tools,                  
        response_mime_type="application/json",
        response_schema=TechnicalAssessment,
        temperature=0.0
    )
    
    chat = client.chats.create(model='gemini-3.5-flash-lite', config=config)
    response = chat.send_message(request.query)
    
    # --- NEW: Intercept and Inject the Disclaimer ---
    
    # 1. Convert the AI's response into a Python dictionary
    if response.parsed:
        final_data = response.parsed.model_dump()
    else:
        final_data = json.loads(response.text)
        
    # 2. Hardcode the exact legal warning (The AI cannot alter this)
    final_data["disclaimer"] = (
        "⚠️ NOT FINANCIAL ADVICE: This analysis is generated by an experimental AI model. "
        "Cryptocurrency markets are highly unpredictable and subject to extreme volatility. "
        "The data provided may be delayed, inaccurate, or incomplete. Always conduct your "
        "own research and consult a licensed financial advisor before making trading decisions."
    )
    
    # 3. Send the completed package to the user/frontend
    return final_data

# ----------------------------------------------------------------------
# CANDLE CHART DATA ENDPOINT
# ----------------------------------------------------------------------
@app.get("/api/chart/{ticker}")
def get_chart_data(ticker: str, timeframe: str = "1M"):
    """
    Fetches raw OHLCV candlestick data for the TradingView frontend chart.
    Timeframes: 1D (5-min intervals), 1W (1-hour), 1M (1-day), 1Y (1-day)
    """
    try:
        symbol = _normalize_ticker(ticker)
        timeframe = timeframe.upper()
        
        # 1. Map the frontend buttons to Yahoo Finance intervals
        if timeframe == "1D":
            period = "1d"
            interval = "5m"
        elif timeframe == "1W":
            period = "7d"
            interval = "1h"
        elif timeframe == "1M":
            period = "1mo"
            interval = "1d"
        elif timeframe == "1Y":
            period = "1y"
            interval = "1d"
        else:
            period = "1mo"
            interval = "1d"
            
        # 2. Fetch the data
        tk = yf.Ticker(symbol)
        df = tk.history(period=period, interval=interval)
        
        if df.empty:
            raise HTTPException(status_code=404, detail=f"No chart data found for {symbol}")
            
        # 3. Format the data EXACTLY how TradingView Lightweight Charts expects it
        chart_data = []
        for index, row in df.iterrows():
            # Lightweight charts requires UNIX timestamps in exact SECONDS (not milliseconds)
            timestamp_seconds = int(index.timestamp())
            
            chart_data.append({
                "time": timestamp_seconds, 
                "open": round(row["Open"], 2),
                "high": round(row["High"], 2),
                "low": round(row["Low"], 2),
                "close": round(row["Close"], 2),
                "value": round(row["Volume"], 2) # Adding volume in case you want a volume bar chart later
            })
            
        return {
            "ticker": symbol, 
            "timeframe": timeframe,
            "data": chart_data
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ----------------------------------------------------------------------
# COIN TABLE DATA ENDPOINT
# ----------------------------------------------------------------------
@app.get("/api/top-coins")
def get_top_coins(limit: int = 50):
    """
    Fetches the top cryptocurrencies using the free, keyless CoinPaprika API.
    Bypasses Indonesian ISP blocks and avoids CoinGecko's strict bot protection.
    """
    try:
        url = "https://api.coinpaprika.com/v1/tickers"
        
        # A simple User-Agent header is always good practice
        headers = {"User-Agent": "Quantitative-Market-Analyst/1.0"}
        
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
        
        data = response.json()
        
        # CoinPaprika returns thousands of coins, we just slice the top 50
        top_coins_data = data[:limit]
        
        formatted_coins = []
        for coin in top_coins_data:
            usd_data = coin.get("quotes", {}).get("USD", {})
            
            formatted_coins.append({
                "id": coin.get("id"),                 
                "rank": int(coin.get("rank", 0)),
                "symbol": coin.get("symbol", "").upper(),     
                "name": coin.get("name", ""),
                "price_usd": round(float(usd_data.get("price", 0)), 2),
                "market_cap_usd": round(float(usd_data.get("market_cap", 0)), 2),
                "volume_24h_usd": round(float(usd_data.get("volume_24h", 0)), 2),
                "change_24h_pct": round(float(usd_data.get("percent_change_24h", 0)), 2),
            })
            
        return {"coins": formatted_coins}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch market overview: {str(e)}")