import json
from fastapi import FastAPI
from pydantic import BaseModel
from typing import Literal
from google import genai
from google.genai import types
from dotenv import load_dotenv
from fastapi.middleware.cors import CORSMiddleware

# Change your import at the top of main.py to include _normalize_ticker
from crypto_tools import CRYPTO_TOOLS, ADVANCED_CRYPTO_TOOLS, _normalize_ticker 
import yfinance as yf # Make sure yfinance is imported in main.py
from fastapi import HTTPException # Add this to handle errors safely

load_dotenv()

# 2. The Blueprint
class TechnicalAssessment(BaseModel):
    ticker: str
    current_price: float
    stance: Literal["BULLISH", "BEARISH", "NEUTRAL"]
    direct_verdict: str
    risk_assessment: str
    tactical_recommendation: str
    key_observations: list[str]
    disclaimer: str # <--- Add this field

# 3. Initialize Web Server and AI
app = FastAPI()
client = genai.Client()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class QueryRequest(BaseModel):
    query: str

@app.post("/api/analyze")
def analyze_market(request: QueryRequest):
    print(f"\n======================================")
    print(f"Incoming user query: {request.query}")
    
    all_tools = CRYPTO_TOOLS + ADVANCED_CRYPTO_TOOLS
    
    system_prompt = (
        "You are an elite quantitative crypto strategist. "
        "You have access to 8 advanced market tools. "
        "1. Run the relevant tools to gather data. "
        "2. Directly answer their question in 'direct_verdict' using risk/reward principles. "
        "3. Evaluate the downside in 'risk_assessment'. "
        "4. Outline clear tactical next steps in 'tactical_recommendation'. "
        "5. Leave the 'disclaimer' field empty; the system will auto-fill it."
    )
    
    config = types.GenerateContentConfig(
        system_instruction=system_prompt, 
        tools=all_tools,                  
        response_mime_type="application/json",
        response_schema=TechnicalAssessment,
        temperature=0.0
    )
    
    chat = client.chats.create(model='gemini-3.5-flash-lite', config=config)
    response = chat.send_message(request.query)
    
    # --- NEW: Intercept and Inject the Disclaimer ---
    
    # 1. Convert the AI's response into a Python dictionary
    if response.parsed:
        final_data = response.parsed.model_dump()
    else:
        final_data = json.loads(response.text)
        
    # 2. Hardcode the exact legal warning (The AI cannot alter this)
    final_data["disclaimer"] = (
        "⚠️ NOT FINANCIAL ADVICE: This analysis is generated by an experimental AI model. "
        "Cryptocurrency markets are highly unpredictable and subject to extreme volatility. "
        "The data provided may be delayed, inaccurate, or incomplete. Always conduct your "
        "own research and consult a licensed financial advisor before making trading decisions."
    )
    
    # 3. Send the completed package to the user/frontend
    return final_data


@app.get("/api/chart/{ticker}")
def get_chart_data(ticker: str, timeframe: str = "1M"):
    """
    Fetches raw OHLCV candlestick data for the TradingView frontend chart.
    Timeframes: 1D (5-min intervals), 1W (1-hour), 1M (1-day), 1Y (1-day)
    """
    try:
        symbol = _normalize_ticker(ticker)
        timeframe = timeframe.upper()
        
        # 1. Map the frontend buttons to Yahoo Finance intervals
        if timeframe == "1D":
            period = "1d"
            interval = "5m"
        elif timeframe == "1W":
            period = "7d"
            interval = "1h"
        elif timeframe == "1M":
            period = "1mo"
            interval = "1d"
        elif timeframe == "1Y":
            period = "1y"
            interval = "1d"
        else:
            period = "1mo"
            interval = "1d"
            
        # 2. Fetch the data
        tk = yf.Ticker(symbol)
        df = tk.history(period=period, interval=interval)
        
        if df.empty:
            raise HTTPException(status_code=404, detail=f"No chart data found for {symbol}")
            
        # 3. Format the data EXACTLY how TradingView Lightweight Charts expects it
        chart_data = []
        for index, row in df.iterrows():
            # Lightweight charts requires UNIX timestamps in exact SECONDS (not milliseconds)
            timestamp_seconds = int(index.timestamp())
            
            chart_data.append({
                "time": timestamp_seconds, 
                "open": round(row["Open"], 2),
                "high": round(row["High"], 2),
                "low": round(row["Low"], 2),
                "close": round(row["Close"], 2),
                "value": round(row["Volume"], 2) # Adding volume in case you want a volume bar chart later
            })
            
        return {
            "ticker": symbol, 
            "timeframe": timeframe,
            "data": chart_data
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))