import json
import requests
import os
import time # <-- Added for caching
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Literal
from google import genai
from google.genai import types
from dotenv import load_dotenv
from fastapi.middleware.cors import CORSMiddleware
from crypto_tools import CRYPTO_TOOLS, ADVANCED_CRYPTO_TOOLS, _normalize_ticker 
import yfinance as yf 
import logging

load_dotenv()

# Configure the logger
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# The Blueprint
class TechnicalAssessment(BaseModel):
    ticker: str
    current_price: float
    stance: Literal["BULLISH", "BEARISH", "NEUTRAL"]
    direct_verdict: str
    risk_assessment: str
    tactical_recommendation: str
    key_observations: list[str]
    disclaimer: str # <--- Add this field

# Initialize Web Server and AI
app = FastAPI()
client = genai.Client()

# Dynamically build the allowed origins list
origins = [
    "http://localhost:5173",  # Always allow your local laptop
]

# Check if we are running in the cloud and have a live frontend URL
live_frontend_url = os.getenv("FRONTEND_URL")
if live_frontend_url:
    origins.append(live_frontend_url)

# Apply the security rules
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins, 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class QueryRequest(BaseModel):
    query: str

# ----------------------------------------------------------------------
# AI MODEL MARKET ANALYSIS ENDPOINT
# ----------------------------------------------------------------------
@app.post("/api/analyze")
def analyze_market(request: QueryRequest):
    print(f"\n======================================")
    logger.info(f"Incoming user query: {request.query}")
    
    all_tools = CRYPTO_TOOLS + ADVANCED_CRYPTO_TOOLS
    
    system_prompt = (
        "You are an elite quantitative crypto strategist. "
        "You have access to 8 advanced market tools. "
        "1. Run the relevant tools to gather data. "
        "2. Directly answer their question in 'direct_verdict' using risk/reward principles. "
        "3. Evaluate the downside in 'risk_assessment'. "
        "4. Outline clear tactical next steps in 'tactical_recommendation'. "
        "5. Leave the 'disclaimer' field empty; the system will auto-fill it."
    )
    
    config = types.GenerateContentConfig(
        system_instruction=system_prompt, 
        tools=all_tools,                  
        response_mime_type="application/json",
        response_schema=TechnicalAssessment,
        temperature=0.0
    )
    
    chat = client.chats.create(model='gemini-3.5-flash-lite', config=config)
    response = chat.send_message(request.query)
    
    # 1. Convert the AI's response into a Python dictionary
    if response.parsed:
        final_data = response.parsed.model_dump()
    else:
        final_data = json.loads(response.text)
        
    # 2. Hardcode the exact legal warning (The AI cannot alter this)
    disclaimer = (
        "⚠️ NOT FINANCIAL ADVICE: This analysis is generated by an experimental AI model. "
        "Cryptocurrency markets are highly unpredictable and subject to extreme volatility. "
        "The data provided may be delayed, inaccurate, or incomplete. Always conduct your "
        "own research and consult a licensed financial advisor before making trading decisions."
    )
    final_data["disclaimer"] = disclaimer
    
    # 3. Format the structured JSON into a beautiful Markdown string for the Chat UI
    # We use formatting safely with .get() in case the AI missed a field
    ticker = final_data.get('ticker', 'Unknown')
    stance = final_data.get('stance', 'NEUTRAL')
    price = final_data.get('current_price', 0.0)
    
    # Choose a color indicator for the stance
    stance_icon = "🟢" if stance == "BULLISH" else "🔴" if stance == "BEARISH" else "🟡"
    
    markdown_chat_reply = f"""### {stance_icon} {ticker} Analysis
**Current Price:** ${price:,.2f} | **Stance:** {stance}

**Direct Verdict**
{final_data.get('direct_verdict', '')}

**Risk Assessment**
{final_data.get('risk_assessment', '')}

**Tactical Recommendation**
{final_data.get('tactical_recommendation', '')}

**Key Observations**
"""
    # Append the bullet points
    for obs in final_data.get('key_observations', []):
        markdown_chat_reply += f"- {obs}\n"
        
    # Append the disclaimer in italics
    markdown_chat_reply += f"\n*{disclaimer}*"

    # 4. Send it back in the exact format the React frontend AiAssistant.jsx expects!
    return {"response": markdown_chat_reply}

# ----------------------------------------------------------------------
# CANDLE CHART DATA ENDPOINT
# ----------------------------------------------------------------------
@app.get("/api/chart/{ticker}")
def get_chart_data(ticker: str, timeframe: str = "1D"):
    """
    Fetches raw OHLCV candlestick data for the TradingView frontend chart.
    Timeframes now represent the CANDLE SIZE (TradingView style).
    """
    try:
        symbol = _normalize_ticker(ticker)
        timeframe = timeframe.upper()
        
        # 1. Map frontend buttons to Yahoo Finance intervals (Candle Size)
        if timeframe == "15M":
            period = "5d"       # 5 days total of 15-minute candles
            interval = "15m"
        elif timeframe == "1H":
            period = "1mo"      # 1 month total of 1-hour candles
            interval = "1h"
        elif timeframe == "1D":
            period = "2y"       # 2 years total of 1-day candles
            interval = "1d"
        elif timeframe == "1W":
            period = "5y"       # 5 years total of 1-week candles
            interval = "1wk"
        else:
            period = "2y"
            interval = "1d"
            
        # 2. Fetch the data
        tk = yf.Ticker(symbol)
        df = tk.history(period=period, interval=interval)
        
        if df.empty:
            raise HTTPException(status_code=404, detail=f"No chart data found for {symbol}")
            
        # 3. Format the data EXACTLY how TradingView Lightweight Charts expects it
        chart_data = []
        for index, row in df.iterrows():
            # Lightweight charts requires UNIX timestamps in exact SECONDS (not milliseconds)
            timestamp_seconds = int(index.timestamp())
            
            chart_data.append({
                "time": timestamp_seconds, 
                "open": round(row["Open"], 2),
                "high": round(row["High"], 2),
                "low": round(row["Low"], 2),
                "close": round(row["Close"], 2),
                "value": round(row["Volume"], 2) # Adding volume in case you want a volume bar chart later
            })
            
        return {
            "ticker": symbol, 
            "timeframe": timeframe,
            "data": chart_data
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ----------------------------------------------------------------------
# COIN TABLE DATA ENDPOINT (WITH CACHING)
# ----------------------------------------------------------------------
# 1. Create a memory dictionary to hold the cached data
market_cache = {
    "data": None,
    "last_fetched": 0
}
CACHE_DURATION = 300  # 300 seconds = 5 minutes

@app.get("/api/top-coins")
def get_top_coins(limit: int = 50):
    """
    Fetches the top cryptocurrencies using the free, keyless CoinPaprika API.
    Includes a 5-minute cache to prevent rate-limiting in production.
    """
    current_time = time.time()
    
    # 2. Check if we have fresh data in the cache
    if market_cache["data"] and (current_time - market_cache["last_fetched"] < CACHE_DURATION):
        logger.info("Serving market data from cache!")
        return {"coins": market_cache["data"]}
        
    # 3. If cache is empty or old, fetch new data from the API
    try:
        logger.info("Fetching fresh market data from CoinPaprika API...")
        url = "https://api.coinpaprika.com/v1/tickers"
        headers = {"User-Agent": "Quantitative-Market-Analyst/1.0"}
        
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
        
        data = response.json()
        top_coins_data = data[:limit]
        
        formatted_coins = []
        for coin in top_coins_data:
            usd_data = coin.get("quotes", {}).get("USD", {})
            formatted_coins.append({
                "id": coin.get("id"),                
                "rank": int(coin.get("rank", 0)),
                "symbol": coin.get("symbol", "").upper(),     
                "name": coin.get("name", ""),
                "price_usd": round(float(usd_data.get("price", 0)), 2),
                "market_cap_usd": round(float(usd_data.get("market_cap", 0)), 2),
                "volume_24h_usd": round(float(usd_data.get("volume_24h", 0)), 2),
                "change_24h_pct": round(float(usd_data.get("percent_change_24h", 0)), 2),
            })
            
        # 4. Save the new formatted data into the cache memory
        market_cache["data"] = formatted_coins
        market_cache["last_fetched"] = current_time
            
        return {"coins": formatted_coins}
        
    except Exception as e:
        # 5. Fallback: If CoinPaprika API fails, try to serve the old cache data instead of crashing
        if market_cache["data"]:
            logger.warning(f"API failed, falling back to old cache. Error: {str(e)}")
            return {"coins": market_cache["data"]}
            
        raise HTTPException(status_code=500, detail=f"Failed to fetch market overview: {str(e)}")